create table if not exists public.cycle_sponsorships (
  id bigint generated by default as identity primary key,
  cycle_id bigint not null unique references public.voting_cycles(id) on delete cascade,
  sponsor_name text not null,
  sponsor_link text not null,
  banner_r2_key text not null,
  is_active boolean not null default true,
  starts_at timestamptz,
  ends_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.sponsor_tracking_events (
  id bigint generated by default as identity primary key,
  sponsorship_id bigint not null references public.cycle_sponsorships(id) on delete cascade,
  event_type text not null check (event_type in ('impression', 'click')),
  surface text not null check (
    surface in (
      'home_hud',
      'vote_modal',
      'history_modal',
      'fame_modal',
      'shame_modal'
    )
  ),
  viewer_hash text not null,
  created_at timestamptz not null default now()
);

create index if not exists cycle_sponsorships_cycle_id_idx
  on public.cycle_sponsorships (cycle_id);

create index if not exists sponsor_tracking_events_lookup_idx
  on public.sponsor_tracking_events (
    sponsorship_id,
    event_type,
    surface,
    viewer_hash,
    created_at desc
  );

create index if not exists sponsor_tracking_events_report_idx
  on public.sponsor_tracking_events (
    sponsorship_id,
    event_type,
    created_at desc
  );
