create table if not exists public.coin_launches (
  id bigint generated by default as identity primary key,
  chain text not null,
  platform text not null,
  token_symbol text,
  contract_address text,
  launch_url text,
  explorer_url text,
  is_active boolean not null default false,
  is_primary boolean not null default false,
  display_order integer not null default 100,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists coin_launches_active_display_order_idx
  on public.coin_launches (is_active, display_order);

create index if not exists coin_launches_primary_idx
  on public.coin_launches (display_order, id)
  where is_primary = true;

alter table public.coin_launches enable row level security;

comment on table public.coin_launches is
  'Stores public token and launch link entries shown by the site.';
