begin;

create table if not exists public.homepage_info_blocks (
  id bigint generated by default as identity primary key,
  seed_key text unique,
  title text,
  body text not null,
  display_order integer not null default 100,
  is_active boolean not null default true,
  link_label text,
  link_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by text,
  updated_by text,
  constraint homepage_info_blocks_seed_key_check check (
    seed_key is null
    or (
      seed_key = btrim(seed_key)
      and seed_key ~ '^[a-z0-9-]+$'
      and char_length(seed_key) between 1 and 100
    )
  ),
  constraint homepage_info_blocks_title_check check (
    title is null
    or (
      title = btrim(title)
      and char_length(title) between 1 and 120
    )
  ),
  constraint homepage_info_blocks_body_check check (
    body = btrim(body)
    and char_length(body) between 1 and 5000
  ),
  constraint homepage_info_blocks_display_order_check check (
    display_order between 0 and 100000
  ),
  constraint homepage_info_blocks_link_pair_check check (
    (link_label is null and link_url is null)
    or (link_label is not null and link_url is not null)
  ),
  constraint homepage_info_blocks_link_label_check check (
    link_label is null
    or (
      link_label = btrim(link_label)
      and char_length(link_label) between 1 and 100
    )
  ),
  constraint homepage_info_blocks_link_url_check check (
    link_url is null
    or (
      link_url = btrim(link_url)
      and char_length(link_url) between 1 and 2048
      and position(E'\\' in link_url) = 0
      and (
        (
          left(link_url, 1) = '/'
          and left(link_url, 2) <> '//'
        )
        or link_url ~* '^https://'
      )
    )
  ),
  constraint homepage_info_blocks_created_by_check check (
    created_by is null
    or (
      created_by = btrim(created_by)
      and char_length(created_by) between 1 and 128
    )
  ),
  constraint homepage_info_blocks_updated_by_check check (
    updated_by is null
    or (
      updated_by = btrim(updated_by)
      and char_length(updated_by) between 1 and 128
    )
  )
);

create index if not exists homepage_info_blocks_active_order_idx
  on public.homepage_info_blocks (display_order, id)
  where is_active = true;

create or replace function public.set_homepage_info_blocks_updated_at()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists homepage_info_blocks_updated_at_trigger
  on public.homepage_info_blocks;

create trigger homepage_info_blocks_updated_at_trigger
before update on public.homepage_info_blocks
for each row
execute function public.set_homepage_info_blocks_updated_at();

alter table public.homepage_info_blocks enable row level security;

revoke all on table public.homepage_info_blocks
  from public, anon, authenticated;
revoke all on sequence public.homepage_info_blocks_id_seq
  from public, anon, authenticated;

grant select (
  id,
  title,
  body,
  display_order,
  is_active,
  link_label,
  link_url
) on public.homepage_info_blocks to anon, authenticated;

grant all on table public.homepage_info_blocks to service_role;
grant select, usage on sequence public.homepage_info_blocks_id_seq
  to service_role;

drop policy if exists homepage_info_blocks_public_active_select
  on public.homepage_info_blocks;

create policy homepage_info_blocks_public_active_select
  on public.homepage_info_blocks
  for select
  to anon, authenticated
  using (is_active = true);

insert into public.homepage_info_blocks (
  seed_key,
  title,
  body,
  display_order,
  is_active
)
values
  (
    'about',
    'ABOUT',
    $about$CancerCulture is a community-driven meme competition built around creativity and chaos.

The name represents how memes and narratives spread, fast, irrational, and everywhere.

Each cycle is its own competition. No algorithms, no hidden rules, just memes and vibes.

Create something, upload it, and let the community decide.

Win or lose, you're part of the culture.$about$,
    100,
    true
  ),
  (
    'how-it-works',
    'HOW IT WORKS',
    $how$Each cycle is a standalone meme competition.

You get:

• 1 submission
• 2 votes

No self-voting. Submissions stay anonymous during the cycle.

When it ends, votes decide the winners.

Rewards are paid in Solana and split if needed.

Winners choose: keep it, donate, or split.$how$,
    200,
    true
  )
on conflict (seed_key) do nothing;

comment on table public.homepage_info_blocks is
  'Admin-managed public information cards rendered in the Homepage Info section.';

commit;
