begin;

set local lock_timeout = '5s';
set local statement_timeout = '60s';

do $preflight$
begin
  if (select count(*) from public.capability_catalog) <> 25
    or (select count(*) from public.capability_catalog where is_active) <> 23
    or (
      select count(*)
      from public.capability_catalog
      where is_active and assignable_to_non_admin
    ) <> 23 then
    raise exception using
      errcode = '55000',
      message = 'RULES_CONTENT_CAPABILITY_BASELINE_MISMATCH';
  end if;

  if not exists (
    select 1
    from public.capability_catalog
    where key = 'cycles.manage'
      and implementation_version = 1
      and definition_hash =
        '4f3e07f01bc453f594994689c3049e698ca2bd1d1c99e75927d161056033f710'
      and is_active
      and assignable_to_non_admin
  ) then
    raise exception using
      errcode = '55000',
      message = 'RULES_CONTENT_PREVIOUS_CUTOVER_MISMATCH';
  end if;

  if exists (
    select 1 from public.capability_catalog where key = 'rules.manage'
  )
    or to_regclass('public.content_documents') is not null
    or to_regclass('public.content_revisions') is not null
    or to_regclass('public.content_publications') is not null
    or to_regclass('public.content_management_requests') is not null
    or to_regprocedure('public.assert_rules_manager(text)') is not null
    or to_regprocedure('public.assert_rules_content_payload(jsonb)') is not null
    or to_regprocedure(
      'public.manage_rules_content(text,text,bigint,jsonb,boolean,uuid)'
    ) is not null then
    raise exception using
      errcode = '55000',
      message = 'RULES_CONTENT_TARGET_ALREADY_PRESENT';
  end if;

  if to_regclass('public.rules_meta') is null
    or to_regclass('public.user_logs') is null
    or to_regclass('public.admin_action_logs') is null
    or to_regclass('public.team_members') is null
    or to_regclass('public.team_roles') is null
    or to_regclass('public.team_role_capabilities') is null
    or (select count(*) from public.rules_meta where id = 1) <> 1
    or exists (
      select 1
      from public.rules_meta
      where id = 1 and current_version <= 0
    ) then
    raise exception using
      errcode = '55000',
      message = 'RULES_CONTENT_DEPENDENCY_MISMATCH';
  end if;
end;
$preflight$;

insert into public.capability_catalog (
  key,
  display_name,
  description,
  category,
  included_actions,
  excluded_actions,
  risk_level,
  assignable_to_non_admin,
  is_active,
  implementation_version,
  definition_hash
)
values (
  'rules.manage',
  'Manage Rules',
  'Create and edit the Rules draft, preview the pending revision, and publish validated Rules with an explicit material-change decision that atomically controls Rules acceptance.',
  'Content',
  array[
    'View the current published Rules and any pending draft in the Content area.',
    'Save validated ordered Rules sections as a versioned draft with optimistic concurrency.',
    'Publish the current draft and explicitly classify text-only changes as material or non-material.',
    'Automatically require a new Rules acceptance version when sections are added or removed.'
  ]::text[],
  array[
    'Managing FAQ, Homepage Info Boxes, Coin Launch Links, or other content.',
    'Changing user acceptance records directly or bypassing rules_meta.',
    'Managing roles, permissions, team membership, or Owner access.',
    'Deleting or rewriting Rules revision, request, or publication history.'
  ]::text[],
  'high',
  true,
  true,
  1,
  'd7097dece0897ddcd924010a9a8cd48f427512231eaf7da77a28005536720887'
);

create table public.content_documents (
  key text primary key,
  state_version bigint not null default 1,
  published_revision_id bigint,
  draft_revision_id bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  updated_by_discord_user_id text,
  constraint content_documents_key_check
    check (key in ('rules', 'faq')),
  constraint content_documents_state_version_check
    check (state_version > 0),
  constraint content_documents_actor_check
    check (
      updated_by_discord_user_id is null
      or (
        char_length(updated_by_discord_user_id) between 1 and 100
        and updated_by_discord_user_id ~ '^[0-9]+$'
      )
    )
);

create table public.content_revisions (
  id bigint generated by default as identity primary key,
  document_key text not null references public.content_documents(key),
  revision_number bigint not null,
  content jsonb not null,
  content_hash text not null,
  created_at timestamptz not null default now(),
  created_by_discord_user_id text,
  constraint content_revisions_document_revision_unique
    unique (document_key, revision_number),
  constraint content_revisions_document_id_unique
    unique (document_key, id),
  constraint content_revisions_revision_number_check
    check (revision_number > 0),
  constraint content_revisions_content_object_check
    check (jsonb_typeof(content) = 'object'),
  constraint content_revisions_hash_check
    check (content_hash ~ '^[0-9a-f]{64}$'),
  constraint content_revisions_actor_check
    check (
      created_by_discord_user_id is null
      or (
        char_length(created_by_discord_user_id) between 1 and 100
        and created_by_discord_user_id ~ '^[0-9]+$'
      )
    )
);

alter table public.content_documents
  add constraint content_documents_published_revision_fk
  foreign key (key, published_revision_id)
  references public.content_revisions(document_key, id),
  add constraint content_documents_draft_revision_fk
  foreign key (key, draft_revision_id)
  references public.content_revisions(document_key, id),
  add constraint content_documents_distinct_revision_check
  check (
    draft_revision_id is null
    or published_revision_id is null
    or draft_revision_id <> published_revision_id
  );

create table public.content_publications (
  id bigint generated by default as identity primary key,
  document_key text not null references public.content_documents(key),
  event_type text not null,
  revision_id bigint not null,
  previous_revision_id bigint,
  requested_material_change boolean,
  effective_material_change boolean not null,
  structure_changed boolean not null,
  previous_rules_version integer not null,
  rules_version integer not null,
  request_id uuid,
  published_at timestamptz not null default now(),
  published_by_discord_user_id text,
  constraint content_publications_event_type_check
    check (event_type in ('bootstrap', 'publish')),
  constraint content_publications_revision_fk
    foreign key (document_key, revision_id)
    references public.content_revisions(document_key, id),
  constraint content_publications_previous_revision_fk
    foreign key (document_key, previous_revision_id)
    references public.content_revisions(document_key, id),
  constraint content_publications_rules_version_check
    check (
      previous_rules_version > 0
      and rules_version > 0
      and rules_version >= previous_rules_version
    ),
  constraint content_publications_actor_check
    check (
      published_by_discord_user_id is null
      or (
        char_length(published_by_discord_user_id) between 1 and 100
        and published_by_discord_user_id ~ '^[0-9]+$'
      )
    ),
  constraint content_publications_bootstrap_shape_check
    check (
      (event_type = 'bootstrap'
        and requested_material_change is null
        and not effective_material_change
        and not structure_changed
        and request_id is null
        and published_by_discord_user_id is null)
      or
      (event_type = 'publish'
        and requested_material_change is not null
        and request_id is not null
        and published_by_discord_user_id is not null)
    )
);

create table public.content_management_requests (
  idempotency_key uuid primary key,
  actor_discord_user_id text not null,
  operation text not null,
  request_hash text not null,
  request_payload jsonb not null,
  result jsonb not null,
  created_at timestamptz not null default now(),
  constraint content_management_requests_actor_check
    check (
      char_length(actor_discord_user_id) between 1 and 100
      and actor_discord_user_id ~ '^[0-9]+$'
    ),
  constraint content_management_requests_operation_check
    check (operation in ('save_draft', 'publish')),
  constraint content_management_requests_hash_check
    check (request_hash ~ '^[0-9a-f]{64}$')
);

alter table public.content_documents owner to postgres;
alter table public.content_revisions owner to postgres;
alter table public.content_publications owner to postgres;
alter table public.content_management_requests owner to postgres;
alter sequence public.content_revisions_id_seq owner to postgres;
alter sequence public.content_publications_id_seq owner to postgres;

alter table public.content_documents enable row level security;
alter table public.content_revisions enable row level security;
alter table public.content_publications enable row level security;
alter table public.content_management_requests enable row level security;

revoke all on table public.content_documents
  from public, anon, authenticated, service_role;
revoke all on table public.content_revisions
  from public, anon, authenticated, service_role;
revoke all on table public.content_publications
  from public, anon, authenticated, service_role;
revoke all on table public.content_management_requests
  from public, anon, authenticated, service_role;
revoke all on sequence public.content_revisions_id_seq
  from public, anon, authenticated, service_role;
revoke all on sequence public.content_publications_id_seq
  from public, anon, authenticated, service_role;

grant select on table public.content_documents to service_role;
grant select on table public.content_revisions to service_role;
grant select on table public.content_publications to service_role;

create or replace function public.prevent_content_history_mutation()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $function$
begin
  raise exception using
    errcode = '55000',
    message = 'CONTENT_HISTORY_APPEND_ONLY';
end;
$function$;

alter function public.prevent_content_history_mutation() owner to postgres;
revoke all on function public.prevent_content_history_mutation()
  from public, anon, authenticated, service_role;

create trigger content_revisions_append_only
before update or delete on public.content_revisions
for each row execute function public.prevent_content_history_mutation();

create trigger content_publications_append_only
before update or delete on public.content_publications
for each row execute function public.prevent_content_history_mutation();

create trigger content_management_requests_append_only
before update or delete on public.content_management_requests
for each row execute function public.prevent_content_history_mutation();

create or replace function public.assert_rules_content_payload(
  p_content jsonb
)
returns void
language plpgsql
immutable
security definer
set search_path = public, pg_temp
as $function$
declare
  v_section jsonb;
  v_item jsonb;
  v_section_id text;
  v_section_ids text[] := '{}'::text[];
  v_paragraph_count integer;
  v_bullet_count integer;
begin
  if p_content is null
    or jsonb_typeof(p_content) <> 'object'
    or octet_length(p_content::text) > 100000
    or (
      select array_agg(key_name order by key_name)
      from jsonb_object_keys(p_content) key_name
    ) is distinct from array[
      'eyebrow',
      'heading',
      'introduction',
      'noticeBody',
      'noticeTitle',
      'schemaVersion',
      'sections'
    ]::text[]
    or jsonb_typeof(p_content -> 'schemaVersion') <> 'number'
    or (p_content ->> 'schemaVersion')::numeric <> 1
    or jsonb_typeof(p_content -> 'eyebrow') <> 'string'
    or char_length(btrim(p_content ->> 'eyebrow')) not between 1 and 80
    or jsonb_typeof(p_content -> 'heading') <> 'string'
    or char_length(btrim(p_content ->> 'heading')) not between 1 and 160
    or jsonb_typeof(p_content -> 'introduction') <> 'string'
    or char_length(btrim(p_content ->> 'introduction')) not between 1 and 2000
    or jsonb_typeof(p_content -> 'noticeTitle') <> 'string'
    or char_length(btrim(p_content ->> 'noticeTitle')) not between 1 and 160
    or jsonb_typeof(p_content -> 'noticeBody') <> 'string'
    or char_length(btrim(p_content ->> 'noticeBody')) not between 1 and 2000
    or jsonb_typeof(p_content -> 'sections') <> 'array'
    or jsonb_array_length(p_content -> 'sections') not between 1 and 30 then
    raise exception using
      errcode = '22023',
      message = 'INVALID_RULES_CONTENT_REQUEST';
  end if;

  for v_section in
    select section_row.value
    from jsonb_array_elements(p_content -> 'sections') section_row(value)
  loop
    if jsonb_typeof(v_section) <> 'object'
      or (
        select array_agg(key_name order by key_name)
        from jsonb_object_keys(v_section) key_name
      ) is distinct from array[
        'bullets', 'id', 'paragraphs', 'title'
      ]::text[]
      or jsonb_typeof(v_section -> 'id') <> 'string'
      or jsonb_typeof(v_section -> 'title') <> 'string'
      or jsonb_typeof(v_section -> 'paragraphs') <> 'array'
      or jsonb_typeof(v_section -> 'bullets') <> 'array' then
      raise exception using
        errcode = '22023',
        message = 'INVALID_RULES_CONTENT_REQUEST';
    end if;

    v_section_id := btrim(v_section ->> 'id');
    v_paragraph_count := jsonb_array_length(v_section -> 'paragraphs');
    v_bullet_count := jsonb_array_length(v_section -> 'bullets');

    if char_length(v_section_id) not between 1 and 80
      or v_section_id !~ '^[a-z0-9]+(-[a-z0-9]+)*$'
      or v_section_id = any(v_section_ids)
      or char_length(btrim(v_section ->> 'title')) not between 1 and 160
      or v_paragraph_count > 30
      or v_bullet_count > 40
      or (v_paragraph_count = 0 and v_bullet_count = 0) then
      raise exception using
        errcode = '22023',
        message = 'INVALID_RULES_CONTENT_REQUEST';
    end if;

    v_section_ids := array_append(v_section_ids, v_section_id);

    for v_item in
      select paragraph_row.value
      from jsonb_array_elements(v_section -> 'paragraphs') paragraph_row(value)
    loop
      if jsonb_typeof(v_item) <> 'string'
        or char_length(btrim(v_item #>> '{}')) not between 1 and 2000 then
        raise exception using
          errcode = '22023',
          message = 'INVALID_RULES_CONTENT_REQUEST';
      end if;
    end loop;

    for v_item in
      select bullet_row.value
      from jsonb_array_elements(v_section -> 'bullets') bullet_row(value)
    loop
      if jsonb_typeof(v_item) <> 'string'
        or char_length(btrim(v_item #>> '{}')) not between 1 and 1000 then
        raise exception using
          errcode = '22023',
          message = 'INVALID_RULES_CONTENT_REQUEST';
      end if;
    end loop;
  end loop;
end;
$function$;

alter function public.assert_rules_content_payload(jsonb) owner to postgres;
revoke all on function public.assert_rules_content_payload(jsonb)
  from public, anon, authenticated, service_role;

create or replace function public.assert_rules_manager(
  p_actor_discord_user_id text
)
returns text
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $function$
declare
  v_actor_id text := btrim(p_actor_discord_user_id);
  v_actor_role text;
begin
  if nullif(v_actor_id, '') is null
    or char_length(v_actor_id) > 100
    or v_actor_id !~ '^[0-9]+$' then
    raise exception using
      errcode = '42501',
      message = 'RULES_CONTENT_FORBIDDEN';
  end if;

  if not exists (
    select 1
    from public.capability_catalog capability_row
    where capability_row.key = 'rules.manage'
      and capability_row.is_active
      and capability_row.assignable_to_non_admin
      and capability_row.implementation_version = 1
      and capability_row.definition_hash =
        'd7097dece0897ddcd924010a9a8cd48f427512231eaf7da77a28005536720887'
  ) then
    raise exception using
      errcode = '55000',
      message = 'RULES_CONTENT_AUTHORIZATION_DEPENDENCY_UNAVAILABLE';
  end if;

  select member_row.role
  into v_actor_role
  from public.team_members member_row
  join public.team_roles role_row
    on role_row.key = member_row.role
   and role_row.is_active
  where member_row.discord_user_id = v_actor_id;

  if not found
    or (
      v_actor_role <> 'admin'
      and not exists (
        select 1
        from public.team_role_capabilities grant_row
        where grant_row.role_key = v_actor_role
          and grant_row.capability_key = 'rules.manage'
      )
    ) then
    raise exception using
      errcode = '42501',
      message = 'RULES_CONTENT_FORBIDDEN';
  end if;

  return v_actor_role;
end;
$function$;

alter function public.assert_rules_manager(text) owner to postgres;
revoke all on function public.assert_rules_manager(text)
  from public, anon, authenticated, service_role;

do $bootstrap$
declare
  v_revision_id bigint;
  v_rules_version integer;
  v_content jsonb := $json$
{
  "schemaVersion": 1,
  "eyebrow": "Rules & Guidelines",
  "heading": "Simple rules. Fair competition.",
  "introduction": "CancerCulture is built around creativity, fair play, and community voting. These rules keep things clear, how to participate, what’s allowed, and how we keep the competition fair for everyone.",
  "noticeTitle": "Current Rules",
  "noticeBody": "These are the rules for the current cycle. If anything changes, you’ll be notified before joining the next one and asked to accept the updated version.",
  "sections": [
    {
      "id": "participation",
      "title": "Participation",
      "paragraphs": [
        "Participation is voluntary. Each cycle is a standalone competition.",
        "Each user may submit one (1) meme and cast one (1) vote per cycle.",
        "Votes are anonymous during an active cycle to ensure fair play.",
        "Self-voting is not allowed and will be blocked by the system."
      ],
      "bullets": []
    },
    {
      "id": "submissions",
      "title": "Submissions",
      "paragraphs": [
        "This platform is about memes. Low-effort uploads, such as simple screenshots from social media, may be disqualified.",
        "If a submission is disqualified, any votes cast for it are removed and cannot be reused in that cycle.",
        "Content does not need to be fully original, but originality increases your chances of winning.",
        "By submitting content, you confirm that you have the right to use it and allow us to display it on the platform.",
        "Submissions may be disqualified if they violate these rules."
      ],
      "bullets": [
        "illegal content (including extreme violence or sexual abuse)",
        "content you do not have rights to",
        "spam or attempts to bypass upload limits"
      ]
    },
    {
      "id": "fair-play",
      "title": "Fair Play",
      "paragraphs": [
        "The goal is to reward creativity, not external influence.",
        "Promoting your submission during an active cycle or encouraging others to vote for you is not allowed.",
        "This includes sharing your submission with the intent of influencing votes through Discord, social media, or other platforms.",
        "If such behavior is detected, it may result in disqualification for the current cycle.",
        "Repeated violations may lead to permanent exclusion from the platform.",
        "Submissions are anonymous during active cycles to support this principle."
      ],
      "bullets": []
    },
    {
      "id": "behavior",
      "title": "Behavior",
      "paragraphs": [
        "Respect other participants and their decisions.",
        "Harassment or abusive behavior will lead to disqualification and may result in a permanent ban."
      ],
      "bullets": [
        "insults, harassment, or targeted attacks",
        "hate speech or threats",
        "doxxing or sharing private information"
      ]
    },
    {
      "id": "rewards",
      "title": "Rewards",
      "paragraphs": [
        "Winners are determined by community voting.",
        "Ties are possible. In such cases, rewards are split equally between winners.",
        "The prize pool varies per cycle and is not guaranteed.",
        "Rewards are paid out in Solana. You are responsible for providing a valid wallet address.",
        "If a winner has an open support request (e.g. wallet issue), payout may be delayed until the issue is resolved.",
        "If a winner does not respond within 24 hours after being contacted regarding an issue, they may be excluded from the payout for that cycle.",
        "If multiple winners exist, the reward may be redistributed among the remaining eligible winners.",
        "If there is a single winner who does not respond, the reward may be carried over to the next cycle."
      ],
      "bullets": []
    },
    {
      "id": "charity-public-profiles",
      "title": "Charity & Public Profiles",
      "paragraphs": [
        "Winners can decide how to handle their reward. Donating is optional.",
        "You may choose to keep 100% of your reward, donate all, or split it.",
        "If you donate at least 1% of your reward and you win, you will be listed on the Wall of Fame.",
        "If you keep 100% of your reward, you will be listed on the Wall of Shame.",
        "These labels are part of the platform’s culture and are not meant as real judgment or harassment.",
        "All choices must be respected. Harassment or attacks based on someone’s decision are not allowed."
      ],
      "bullets": []
    },
    {
      "id": "moderation",
      "title": "Moderation",
      "paragraphs": [
        "We reserve the right to remove submissions, disqualify participants, or restrict access to protect platform integrity.",
        "Moderation decisions are made at our discretion and may not always include a detailed explanation.",
        "Repeated rule violations may result in a permanent ban.",
        "Moderation and system actions are logged for transparency and abuse prevention."
      ],
      "bullets": []
    },
    {
      "id": "technical-limits",
      "title": "Technical & Limits",
      "paragraphs": [
        "The current maximum file size is 4MB.",
        "Repeated failed upload attempts or attempts to bypass system limits may result in temporary blocks or further restrictions.",
        "This block is automatically lifted in the next cycle and does not require support.",
        "We do not guarantee uninterrupted availability of the platform."
      ],
      "bullets": []
    },
    {
      "id": "disclaimer",
      "title": "Disclaimer",
      "paragraphs": [
        "This is not a game of chance. Outcomes are determined by community voting.",
        "Participation is at your own risk.",
        "We are not liable for technical issues, incorrect wallet details, or lost funds.",
        "The platform and its rules may evolve over time."
      ],
      "bullets": []
    },
    {
      "id": "final-note",
      "title": "Final Note",
      "paragraphs": [
        "Keep it creative. Keep it fair. Don't be an idiot."
      ],
      "bullets": []
    }
  ]
}
$json$::jsonb;
begin
  perform public.assert_rules_content_payload(v_content);

  select current_version
  into v_rules_version
  from public.rules_meta
  where id = 1;

  insert into public.content_documents (key, state_version)
  values ('rules', 1);

  insert into public.content_revisions (
    document_key,
    revision_number,
    content,
    content_hash,
    created_by_discord_user_id
  ) values (
    'rules',
    1,
    v_content,
    encode(
      extensions.digest(convert_to(v_content::text, 'UTF8'), 'sha256'),
      'hex'
    ),
    null
  )
  returning id into v_revision_id;

  update public.content_documents
  set published_revision_id = v_revision_id
  where key = 'rules';

  insert into public.content_publications (
    document_key,
    event_type,
    revision_id,
    previous_revision_id,
    requested_material_change,
    effective_material_change,
    structure_changed,
    previous_rules_version,
    rules_version,
    request_id,
    published_by_discord_user_id
  ) values (
    'rules',
    'bootstrap',
    v_revision_id,
    null,
    null,
    false,
    false,
    v_rules_version,
    v_rules_version,
    null,
    null
  );
end;
$bootstrap$;

create or replace function public.manage_rules_content(
  p_actor_discord_user_id text,
  p_operation text,
  p_expected_state_version bigint,
  p_content jsonb,
  p_material_change boolean,
  p_idempotency_key uuid
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $function$
declare
  v_actor_id text := btrim(p_actor_discord_user_id);
  v_actor_role text;
  v_actor_type text;
  v_operation text := lower(btrim(p_operation));
  v_request_payload jsonb;
  v_request_hash text;
  v_existing_hash text;
  v_existing_result jsonb;
  v_document public.content_documents%rowtype;
  v_revision_id bigint;
  v_revision_number bigint;
  v_content_hash text;
  v_draft_content jsonb;
  v_draft_hash text;
  v_published_content jsonb;
  v_published_hash text;
  v_published_ids text[];
  v_draft_ids text[];
  v_structure_changed boolean := false;
  v_effective_material_change boolean;
  v_previous_rules_version integer;
  v_rules_version integer;
  v_result jsonb;
begin
  if p_idempotency_key is null
    or p_expected_state_version is null
    or p_expected_state_version <= 0
    or nullif(v_actor_id, '') is null
    or char_length(v_actor_id) > 100
    or v_operation not in ('save_draft', 'publish')
    or (
      v_operation = 'save_draft'
      and (p_content is null or p_material_change is not null)
    )
    or (
      v_operation = 'publish'
      and (p_content is not null or p_material_change is null)
    ) then
    raise exception using
      errcode = '22023',
      message = 'INVALID_RULES_CONTENT_REQUEST';
  end if;

  v_actor_role := public.assert_rules_manager(v_actor_id);
  v_actor_type := case
    when v_actor_role = 'admin' then 'admin'
    else 'moderator'
  end;

  if v_operation = 'save_draft' then
    perform public.assert_rules_content_payload(p_content);
  end if;

  v_request_payload := jsonb_build_object(
    'operationVersion', 1,
    'actorDiscordUserId', v_actor_id,
    'operation', v_operation,
    'expectedStateVersion', p_expected_state_version,
    'content', p_content,
    'materialChange', p_material_change
  );
  v_request_hash := encode(
    extensions.digest(
      convert_to(v_request_payload::text, 'UTF8'),
      'sha256'
    ),
    'hex'
  );

  perform pg_advisory_xact_lock(
    hashtextextended(p_idempotency_key::text, 0)
  );

  select request_hash, result
  into v_existing_hash, v_existing_result
  from public.content_management_requests
  where idempotency_key = p_idempotency_key;

  if found then
    if v_existing_hash = v_request_hash then
      return jsonb_set(v_existing_result, '{replayed}', 'true'::jsonb);
    end if;

    raise exception using
      errcode = 'PT409',
      message = 'RULES_CONTENT_IDEMPOTENCY_CONFLICT';
  end if;

  perform pg_advisory_xact_lock(
    hashtextextended('content-document:rules', 0)
  );

  select document_row.*
  into v_document
  from public.content_documents document_row
  where document_row.key = 'rules'
  for update;

  if not found then
    raise exception using
      errcode = '55000',
      message = 'RULES_CONTENT_DEPENDENCY_MISMATCH';
  end if;

  if v_document.state_version <> p_expected_state_version then
    raise exception using
      errcode = 'PT409',
      message = 'RULES_CONTENT_STATE_CONFLICT';
  end if;

  select current_version
  into v_rules_version
  from public.rules_meta
  where id = 1
  for update;

  if not found or v_rules_version <= 0 then
    raise exception using
      errcode = '55000',
      message = 'RULES_CONTENT_DEPENDENCY_MISMATCH';
  end if;

  if v_operation = 'save_draft' then
    v_content_hash := encode(
      extensions.digest(convert_to(p_content::text, 'UTF8'), 'sha256'),
      'hex'
    );

    if v_document.draft_revision_id is not null then
      select revision_row.content_hash
      into v_draft_hash
      from public.content_revisions revision_row
      where revision_row.document_key = 'rules'
        and revision_row.id = v_document.draft_revision_id;

      if v_draft_hash = v_content_hash then
        raise exception using
          errcode = 'PT409',
          message = 'RULES_CONTENT_NO_CHANGES';
      end if;
    end if;

    select revision_row.content_hash
    into v_published_hash
    from public.content_revisions revision_row
    where revision_row.document_key = 'rules'
      and revision_row.id = v_document.published_revision_id;

    if v_published_hash is null then
      raise exception using
        errcode = '55000',
        message = 'RULES_CONTENT_DEPENDENCY_MISMATCH';
    end if;

    if v_published_hash = v_content_hash then
      raise exception using
        errcode = 'PT409',
        message = 'RULES_CONTENT_NO_CHANGES';
    end if;

    select coalesce(max(revision_number), 0) + 1
    into v_revision_number
    from public.content_revisions
    where document_key = 'rules';

    insert into public.content_revisions (
      document_key,
      revision_number,
      content,
      content_hash,
      created_by_discord_user_id
    ) values (
      'rules',
      v_revision_number,
      p_content,
      v_content_hash,
      v_actor_id
    )
    returning id into v_revision_id;

    update public.content_documents
    set draft_revision_id = v_revision_id,
        state_version = state_version + 1,
        updated_at = transaction_timestamp(),
        updated_by_discord_user_id = v_actor_id
    where key = 'rules'
    returning state_version into v_document.state_version;

    insert into public.admin_action_logs (
      actor_type, actor_id, action, target_type, target_id, meta
    ) values (
      v_actor_type,
      v_actor_id,
      'rules_draft_saved',
      'content_document',
      'rules',
      jsonb_build_object(
        'revision_id', v_revision_id,
        'revision_number', v_revision_number,
        'state_version', v_document.state_version,
        'authorization_capability', 'rules.manage',
        'authorization_role', v_actor_role,
        'request_id', p_idempotency_key
      )
    );

    v_result := jsonb_build_object(
      'operation', v_operation,
      'requestId', p_idempotency_key,
      'stateVersion', v_document.state_version,
      'revisionId', v_revision_id,
      'revisionNumber', v_revision_number,
      'rulesVersion', v_rules_version,
      'materialChange', null,
      'structureChanged', null,
      'replayed', false
    );
  else
    if v_document.draft_revision_id is null then
      raise exception using
        errcode = 'PT409',
        message = 'RULES_CONTENT_NO_DRAFT';
    end if;

    select revision_row.content,
           revision_row.content_hash,
           revision_row.revision_number
    into v_draft_content, v_draft_hash, v_revision_number
    from public.content_revisions revision_row
    where revision_row.document_key = 'rules'
      and revision_row.id = v_document.draft_revision_id;

    select revision_row.content, revision_row.content_hash
    into v_published_content, v_published_hash
    from public.content_revisions revision_row
    where revision_row.document_key = 'rules'
      and revision_row.id = v_document.published_revision_id;

    if v_draft_content is null or v_published_content is null then
      raise exception using
        errcode = '55000',
        message = 'RULES_CONTENT_DEPENDENCY_MISMATCH';
    end if;

    if v_draft_hash = v_published_hash then
      raise exception using
        errcode = 'PT409',
        message = 'RULES_CONTENT_NO_CHANGES';
    end if;

    select coalesce(
      array_agg(section_row.value ->> 'id' order by section_row.value ->> 'id'),
      '{}'::text[]
    )
    into v_published_ids
    from jsonb_array_elements(
      v_published_content -> 'sections'
    ) section_row(value);

    select coalesce(
      array_agg(section_row.value ->> 'id' order by section_row.value ->> 'id'),
      '{}'::text[]
    )
    into v_draft_ids
    from jsonb_array_elements(
      v_draft_content -> 'sections'
    ) section_row(value);

    v_structure_changed := v_published_ids is distinct from v_draft_ids;
    v_effective_material_change :=
      p_material_change or v_structure_changed;
    v_previous_rules_version := v_rules_version;

    if v_effective_material_change then
      update public.rules_meta
      set current_version = current_version + 1,
          updated_at = transaction_timestamp()
      where id = 1
      returning current_version into v_rules_version;
    end if;

    v_revision_id := v_document.draft_revision_id;

    update public.content_documents
    set published_revision_id = draft_revision_id,
        draft_revision_id = null,
        state_version = state_version + 1,
        updated_at = transaction_timestamp(),
        updated_by_discord_user_id = v_actor_id
    where key = 'rules'
    returning state_version into v_document.state_version;

    insert into public.content_publications (
      document_key,
      event_type,
      revision_id,
      previous_revision_id,
      requested_material_change,
      effective_material_change,
      structure_changed,
      previous_rules_version,
      rules_version,
      request_id,
      published_by_discord_user_id
    ) values (
      'rules',
      'publish',
      v_revision_id,
      v_document.published_revision_id,
      p_material_change,
      v_effective_material_change,
      v_structure_changed,
      v_previous_rules_version,
      v_rules_version,
      p_idempotency_key,
      v_actor_id
    );

    insert into public.admin_action_logs (
      actor_type, actor_id, action, target_type, target_id, meta
    ) values (
      v_actor_type,
      v_actor_id,
      'rules_published',
      'content_document',
      'rules',
      jsonb_build_object(
        'revision_id', v_revision_id,
        'revision_number', v_revision_number,
        'state_version', v_document.state_version,
        'requested_material_change', p_material_change,
        'effective_material_change', v_effective_material_change,
        'structure_changed', v_structure_changed,
        'previous_rules_version', v_previous_rules_version,
        'rules_version', v_rules_version,
        'authorization_capability', 'rules.manage',
        'authorization_role', v_actor_role,
        'request_id', p_idempotency_key
      )
    );

    v_result := jsonb_build_object(
      'operation', v_operation,
      'requestId', p_idempotency_key,
      'stateVersion', v_document.state_version,
      'revisionId', v_revision_id,
      'revisionNumber', v_revision_number,
      'rulesVersion', v_rules_version,
      'materialChange', v_effective_material_change,
      'structureChanged', v_structure_changed,
      'replayed', false
    );
  end if;

  insert into public.content_management_requests (
    idempotency_key,
    actor_discord_user_id,
    operation,
    request_hash,
    request_payload,
    result
  ) values (
    p_idempotency_key,
    v_actor_id,
    v_operation,
    v_request_hash,
    v_request_payload,
    v_result
  );

  return v_result;
end;
$function$;

alter function public.manage_rules_content(
  text, text, bigint, jsonb, boolean, uuid
) owner to postgres;
revoke all on function public.manage_rules_content(
  text, text, bigint, jsonb, boolean, uuid
) from public, anon, authenticated;
grant execute on function public.manage_rules_content(
  text, text, bigint, jsonb, boolean, uuid
) to service_role;

comment on function public.manage_rules_content(
  text, text, bigint, jsonb, boolean, uuid
) is
  'Authorizes rules.manage and atomically saves immutable Rules drafts or publishes the current draft with optimistic concurrency, idempotency, append-only history, audit, and controlled rules_meta acceptance versioning.';

do $postflight$
declare
  v_bad_function_count integer;
begin
  if (select count(*) from public.capability_catalog) <> 26
    or (select count(*) from public.capability_catalog where is_active) <> 24
    or (
      select count(*)
      from public.capability_catalog
      where is_active and assignable_to_non_admin
    ) <> 24
    or not exists (
      select 1
      from public.capability_catalog
      where key = 'rules.manage'
        and implementation_version = 1
        and definition_hash =
          'd7097dece0897ddcd924010a9a8cd48f427512231eaf7da77a28005536720887'
        and is_active
        and assignable_to_non_admin
    )
    or exists (
      select 1
      from public.team_role_capabilities
      where capability_key = 'rules.manage'
    )
    or (select count(*) from public.content_documents where key = 'rules') <> 1
    or (
      select count(*)
      from public.content_revisions revision_row
      join public.content_documents document_row
        on document_row.key = revision_row.document_key
       and document_row.published_revision_id = revision_row.id
      where document_row.key = 'rules'
        and document_row.draft_revision_id is null
        and document_row.state_version = 1
        and revision_row.revision_number = 1
    ) <> 1
    or (
      select count(*)
      from public.content_publications
      where document_key = 'rules'
        and event_type = 'bootstrap'
        and rules_version = previous_rules_version
        and not effective_material_change
        and not structure_changed
    ) <> 1 then
    raise exception using
      errcode = '55000',
      message = 'RULES_CONTENT_DATA_POSTFLIGHT_MISMATCH';
  end if;

  select count(*)
  into v_bad_function_count
  from pg_proc function_row
  join pg_namespace namespace_row
    on namespace_row.oid = function_row.pronamespace
  where namespace_row.nspname = 'public'
    and function_row.oid in (
      'public.prevent_content_history_mutation()'::regprocedure,
      'public.assert_rules_content_payload(jsonb)'::regprocedure,
      'public.assert_rules_manager(text)'::regprocedure,
      'public.manage_rules_content(text,text,bigint,jsonb,boolean,uuid)'::regprocedure
    )
    and (
      pg_get_userbyid(function_row.proowner) <> 'postgres'
      or not function_row.prosecdef
      or function_row.proconfig is distinct from
        array['search_path=public, pg_temp']::text[]
    );

  if v_bad_function_count <> 0
    or exists (
      select 1
      from pg_class relation_row
      join pg_namespace namespace_row
        on namespace_row.oid = relation_row.relnamespace
      where namespace_row.nspname = 'public'
        and relation_row.relname in (
          'content_documents',
          'content_revisions',
          'content_publications',
          'content_management_requests'
        )
        and not relation_row.relrowsecurity
    )
    or has_table_privilege('anon', 'public.content_documents', 'select')
    or has_table_privilege('authenticated', 'public.content_documents', 'select')
    or has_table_privilege('anon', 'public.content_revisions', 'select')
    or has_table_privilege('authenticated', 'public.content_revisions', 'select')
    or has_table_privilege('anon', 'public.content_publications', 'select')
    or has_table_privilege('authenticated', 'public.content_publications', 'select')
    or has_table_privilege('service_role', 'public.content_documents', 'insert')
    or has_table_privilege('service_role', 'public.content_documents', 'update')
    or has_table_privilege('service_role', 'public.content_documents', 'delete')
    or has_table_privilege('service_role', 'public.content_revisions', 'insert')
    or has_table_privilege('service_role', 'public.content_revisions', 'update')
    or has_table_privilege('service_role', 'public.content_revisions', 'delete')
    or has_table_privilege('service_role', 'public.content_publications', 'insert')
    or has_table_privilege('service_role', 'public.content_management_requests', 'select')
    or not has_table_privilege('service_role', 'public.content_documents', 'select')
    or not has_table_privilege('service_role', 'public.content_revisions', 'select')
    or not has_table_privilege('service_role', 'public.content_publications', 'select')
    or has_function_privilege(
      'anon',
      'public.manage_rules_content(text,text,bigint,jsonb,boolean,uuid)',
      'execute'
    )
    or has_function_privilege(
      'authenticated',
      'public.manage_rules_content(text,text,bigint,jsonb,boolean,uuid)',
      'execute'
    )
    or not has_function_privilege(
      'service_role',
      'public.manage_rules_content(text,text,bigint,jsonb,boolean,uuid)',
      'execute'
    )
    or has_function_privilege(
      'service_role', 'public.assert_rules_manager(text)', 'execute'
    )
    or has_function_privilege(
      'service_role', 'public.assert_rules_content_payload(jsonb)', 'execute'
    ) then
    raise exception using
      errcode = '55000',
      message = 'RULES_CONTENT_SECURITY_POSTFLIGHT_MISMATCH';
  end if;
end;
$postflight$;

commit;
